config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :recipes
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
# frozen_string_literal: true

# Recipe
class Recipe < ApplicationRecord
  attachment :image
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :material, :make, :point, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  attachment :profile_image

  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeController
class HomeController < ApplicationController
  def index; end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

# RecipesController
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  
  def index
    @recipes = Recipe.all.order(id: :desc).page(params[:page]).per(9)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'レシピを作成しました。'
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'レシピを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to user_path(@recipe.user), notice: 'レシピを削除しました。'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :material, :make, :point, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @users = User.all.page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'プロフィールを更新しました。'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# HomeHelper
module HomeHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

# RecipesHelper
module RecipesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# UsersHelper
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <% if user_signed_in? %>
    <div class="content has-text-centered">
      <p class="is-size-1" style="font-family: mv boli;">Recipelist</p>
    </div>
    <br>
    <div class="columns is-centered">
      <div class="column">
        <figure>
          <div class="home-image"></div>
        </figure>
      </div>
    </div>
  <% else %>
    <div class="content has-text-centered">
      <p class="is-size-1" style="font-family: mv boli;">Recipelist</p>
    </div>  
    <div class="columns is-centered">
      <div class="column is-5">
        <%= link_to 'ログイン', new_user_session_path, class: "button is-warning is-fullwidth" %>
        <br>
        <%= link_to '新規登録', new_user_registration_path, class: "button is-warning is-fullwidth" %>
      </div>
    </div>
    <br>
    <div class="columns is-centered">
      <div class="column">
        <figure>
          <div class="home-image"></div>
        </figure>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipelist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: mv boli;">Recipelist</h1>
        <% end %>
      </div>
    
      <% if user_signed_in? %>
        <div class="navbar-menu">
          <div class="navbar-item">
            <%= link_to 'レシピ一覧', recipes_path, class: "button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to 'レシピ作成', new_recipe_path, class: "button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to 'ユーザー一覧', users_path, class: "button is-warning is-light" %>
          </div>
              
          <div class="navbar-end">
            <div class="navbar-item">
              <%= link_to 'マイページ', user_path(current_user), class: "button is-warning is-light" %>
            </div>
            <div class="navbar-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "button is-warning is-light"%>
            </div>
          </div>
        </div>
      <% else %>
        <div class="navbar-menu">
          <div class="navbar-item">
            <%= link_to 'レシピ一覧', recipes_path, class: "button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to 'ユーザー一覧', users_path, class: "button is-warning is-light" %>
          </div>
              
          <div class="navbar-end">
            <div class="navbar-item">
              <%= link_to 'ログイン', new_user_session_path, class: "button is-warning is-light" %>
            </div>
            <div class="navbar-item">
              <%= link_to '新規登録', new_user_registration_path, class: "button is-warning is-light" %>
            </div>
          </div>
        </div>
      <% end %>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">レシピ編集</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :material, "材料", class: "label" %>
            <%= f.text_area :material, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :make, "作り方", class: "label" %>
            <%= f.text_area :make, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :point, "ポイント", class: "label" %>
            <%= f.text_area :point, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          
          <%= f.submit '更新', class: "button is-success" %>
          
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">レシピ一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag recipe.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class=title><%= link_to recipe.user.name, user_path(recipe.user) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @recipes %>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">レシピ作成</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :material, "材料", class: "label" %>
            <%= f.text_area :material, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :make, "作り方", class: "label" %>
            <%= f.text_area :make, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :point, "ポイント", class: "label" %>
            <%= f.text_area :point, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          
          <%= f.submit '投稿', class: "button is-success" %>
          
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">レシピ詳細</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @recipe, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @recipe.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>材料</th>
                </tr>
                <tr>
                  <td><%= simple_format(@recipe.material) %></td>
                </tr>
                <tr>
                  <th>作り方</th>
                </tr>
                <tr>
                  <td><%= simple_format(@recipe.make) %></td>
                </tr>
                <tr>
                  <th>ポイント</th>
                </tr>
                <tr>
                  <td><%= simple_format(@recipe.point) %></td>
                </tr>
              </table>
              <% if user_signed_in? && @recipe.user.id == current_user.id %>
                <%= link_to '編集', edit_recipe_path(@recipe), class: "button is-success" %>
                <%= link_to '削除', recipe_path(@recipe), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "button is-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-4">
        <div class="panel is-info">
          <p class="panel-heading">投稿者：<%= @recipe.user.name %></p>
          <%= link_to user_path(@recipe.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @recipe.user.name %>さんのマイページへ
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">プロフィール編集</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :name, "ユーザー名", class: "label" %>
            <%= f.text_field :name, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>
          
          <%= f.submit '更新', class: "button is-success" %>
          
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">ユーザー一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure>
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%= link_to user.name, user_path(user) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @users %>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">マイページ</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128" style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <%= @user.name %>
                </td>
                <td>
                  <% if user_signed_in? && current_user.id == @user.id %>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                  <% end %>
                </td>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= simple_format(@user.profile) %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to "レシピを見る", recipe_path(recipe) %>
                  <% if user_signed_in? && recipe.user.id == current_user.id %>
                    <P><%= link_to "レシピを編集する", edit_recipe_path(recipe) %></P>
                    <P><%= link_to "レシピを削除する", recipe_path(recipe), method: :delete, data: { confirm: "本当に削除しますか？" } %></P>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>